change length parameter of I2C transactions and MPU6050_getFIFOBytes from 8 bits to 16 bits
jrowberg/i2cdevlib pull request #773
Opened 2024-12-16 10:13 UTC by mzltn

Change type of length parameter from uint8_t to uint16_t for the following functions (STM32 and STM32HAL):
		I2Cdev_readBits, I2Cdev_readBitsW,
		I2Cdev_readBytes, I2Cdev_readWords,
		I2Cdev_writeBits, I2Cdev_writeBitsW,
		I2Cdev_writeBytes, I2Cdev_writeWords
to allow transactions longer than 255 bytes.

Change length parameter of MPU6050_getFIFOBytes from u8 to u16 to allow transactions longer than 255 bytes.

2024-12-16 12:24 UTC, eku commented
This will break existing code. Can we please find another solution?

2024-12-16 16:32 UTC, mzltn commented
Sorry for possibly overlooking a case. Could you please give me a more specific example of what I'm missing? I'll try to find a better solution.

2024-12-17 08:14 UTC, eku requested changes
I did not mention all lines where increasing length from 8 to 16 Bit breaks code.
Changes in API also breaks external code using this library.

2024-12-17 08:14 UTC, eku commented on STM32/I2Cdev.c
>  	uint16_t bytes_num = len*2;
Possible overflow
```suggestion
	uint32_t bytes_num = len*2;
```

2024-12-17 08:14 UTC, eku commented on STM32/I2Cdev.c
>  	uint16_t bytes_num = len*2+1;
Possible overflow

2024-12-17 08:14 UTC, eku commented on STM32HAL/I2Cdev/I2Cdev.c
> +uint8_t I2Cdev_readBits(uint8_t devAddr, uint8_t regAddr, uint8_t bitStart, uint16_t length, uint8_t *data, uint16_t timeout)
Breaks line 101 (Bit shifts)

2024-12-17 08:14 UTC, eku commented on STM32HAL/I2Cdev/I2Cdev.c
> +uint8_t I2Cdev_readBitsW(uint8_t devAddr, uint8_t regAddr, uint8_t bitStart, uint16_t length, uint16_t *data, uint16_t timeout)
Breaks line 129 (Bit shift)

2024-12-17 12:51 UTC, mzltn commented
Ok, let's close this for now. I'll reopen it if I find a better solution.

2024-12-17 12:51 UTC, closed without merging